language: node_js
node_js:
  - node
notifications:
  slack: progprojgroup24:g841RwdHna5JjgqrSJE5Ex85
before_install:
  - rvm use 2.4.1 --install
script:
  - cd client && yarn && yarn test && cd ../
  - cd rubyServer && bundler install && rake test
env:
  - TZ=Europe/London
