language: node_js
node_js:
  - node
notifications:
  slack: progprojgroup24:g841RwdHna5JjgqrSJE5Ex85
before_install:
  - rvm use ruby --install --latest --binary
script:
  - cd rubyServer && bundler install && rake test
